version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g @angular/cli@17
      # Install Chrome for headless testing
      - apt-get update && apt-get install -y wget gnupg
      - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      - apt-get update && apt-get install -y google-chrome-stable
  pre_build:
    commands:
      - npm install
  build:
    commands:
      # Set Chrome binary path and execute unit tests without watching
      - export CHROME_BIN=/usr/bin/google-chrome
      - ng test --watch=false --browsers=ChromeHeadlessNoSandbox
artifacts:
  base-directory: dist/my-angular-project
  files:
    - '**/*'
